name: NPM Publish

env:
  NODE_VERSION: 16

on:
  release:
    types: [created]

jobs:
  test-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm

      - run: node -v
      - run: npm -v

      - run: npm ci

      - run: npm run build:lib
      - run: npm run test:lib

  publish-npm:
    needs: test-lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: https://registry.npmjs.org/
          cache: npm

      - run: node -v
      - run: npm -v

      - run: npm ci
      - run: npm run build:lib

      - run: npm publish dist/ngx-editor/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
